import db from "./connection";

/**
 * Creates all tables if they don't already exist.
 * Call this once at server startup (in index.ts).
 *
 * "CREATE TABLE IF NOT EXISTS" is safe to call every restart —
 * it does nothing if the table is already there.
 *
 * --- Why JSON columns for some fields? ---
 * SQLite stores flat rows. Fields like `notes`, `accords`, `seasons`,
 * and `galleryImages` are nested arrays/objects in your frontend type.
 * For a single-shop kiosk app where we never need to query *inside*
 * those fields (e.g. "find all perfumes with bergamot as a top note"),
 * storing them as JSON strings is the right tradeoff — simple, fast,
 * and maps directly back to your TypeScript types.
 *
 * If you ever needed to query inside those fields, you'd break them
 * into separate tables (perfume_notes, perfume_accords, etc.) with
 * foreign keys. That's not needed here.
 */
export function createTables() {
  db.exec(`
    -- Main perfumes table
    CREATE TABLE IF NOT EXISTS perfumes (
      -- Identity
      id          TEXT PRIMARY KEY,           -- UUID, generated by the server
      name        TEXT NOT NULL,
      code        TEXT NOT NULL UNIQUE,       -- e.g. "ME-001" — must be unique
      brand       TEXT NOT NULL,
      price       REAL NOT NULL CHECK(price >= 0),

      -- Classification
      gender      TEXT NOT NULL CHECK(gender IN ('Male', 'Female', 'Kids', 'Unisex')),
      category    TEXT NOT NULL CHECK(category IN (
                    'Perfume', 'Brand Perfume',
                    'Luxury Perfume', 'Ultra-Luxury Perfume'
                  )),
      day_night   TEXT NOT NULL CHECK(day_night IN ('Day', 'Night', 'Both')),

      -- Content
      description TEXT NOT NULL DEFAULT '',
      rating      REAL NOT NULL DEFAULT 0 CHECK(rating >= 0 AND rating <= 5),

      -- Images
      main_image     TEXT NOT NULL DEFAULT '',   -- path or URL to main image
      gallery_images TEXT NOT NULL DEFAULT '[]', -- JSON array of image paths

      -- Nested data stored as JSON strings
      -- Shape: [{ name: string, value: number, color: string }]
      accords            TEXT NOT NULL DEFAULT '[]',

      -- Shape: { longevity: string, projection: string, sillage: string }
      fragrance_profile  TEXT NOT NULL DEFAULT '{}',

      -- Shape: ["Winter", "Summer", ...]
      seasons            TEXT NOT NULL DEFAULT '[]',

      -- Shape: { top: [{name, iconUrl}], middle: [...], base: [...] }
      notes              TEXT NOT NULL DEFAULT '{}',

      -- Metadata
      in_stock    INTEGER NOT NULL DEFAULT 1,   -- SQLite has no BOOLEAN; 1=true, 0=false
      created_at  TEXT NOT NULL DEFAULT (datetime('now')),
      updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
    );

    -- Staff requests — when a customer taps "Ask Staff About This"
    CREATE TABLE IF NOT EXISTS staff_requests (
      id           TEXT PRIMARY KEY,
      perfume_id   TEXT NOT NULL REFERENCES perfumes(id) ON DELETE CASCADE,
      perfume_name TEXT NOT NULL,   -- denormalized so we can show it even if perfume is deleted
      station      TEXT,            -- optional: which device/station made the request
      is_resolved  INTEGER NOT NULL DEFAULT 0,  -- 0 = pending, 1 = resolved
      created_at   TEXT NOT NULL DEFAULT (datetime('now')),
      resolved_at  TEXT
    );

    -- Admin users — for protecting the admin panel
    CREATE TABLE IF NOT EXISTS admin_users (
      id            TEXT PRIMARY KEY,
      username      TEXT NOT NULL UNIQUE,
      role          TEXT NOT NULL CHECK(role IN ('admin', 'staff')),
      password_hash TEXT NOT NULL,          -- NEVER store plain text passwords
      created_at    TEXT NOT NULL DEFAULT (datetime('now'))
    );
  `);

  console.log("✅ Database tables ready");
}
