export type Gender = "Male" | "Female" | "Kids" | "Unisex";
export type DayNight = "Day" | "Night" | "Both";
export type Season = "Winter" | "Spring" | "Summer" | "Autumn";
export type Category =
  | "Perfume"
  | "Brand Perfume"
  | "Luxury Perfume"
  | "Ultra-Luxury Perfume";

export interface Accord {
  name: string;
  value: number;
  color: string;
}

export interface FragranceProfile {
  longevity: string;
  projection: string;
  sillage: string;
}

export interface Note {
  name: string;
  iconUrl: string;
}

export interface Notes {
  top: Note[];
  middle: Note[];
  base: Note[];
}

export interface Perfume {
  id: string;
  name: string;
  code: string;
  brand: string;
  price: number;
  gender: Gender;
  category: Category;
  description: string;
  rating: number;
  mainImage: string;
  galleryImages: string[];
  accords: Accord[];
  fragranceProfile: FragranceProfile;
  dayNight: DayNight;
  seasons: Season[];
  notes: Notes;
  inStock: boolean;
  createdAt: string;
  updatedAt: string;
}

// The shape of a raw row coming straight out of SQLite
// (snake_case, JSON strings instead of parsed objects)
export interface PerfumeRow {
  id: string;
  name: string;
  code: string;
  brand: string;
  price: number;
  gender: Gender;
  category: Category;
  description: string;
  rating: number;
  main_image: string;
  gallery_images: string; // JSON string
  accords: string; // JSON string
  fragrance_profile: string; // JSON string
  day_night: DayNight;
  seasons: string; // JSON string
  notes: string; // JSON string
  in_stock: number; // 0 or 1
  created_at: string;
  updated_at: string;
}

export interface StaffRequest {
  id: string;
  perfumeId: string;
  perfumeName: string;
  station?: string;
  isResolved: boolean;
  createdAt: string;
  resolvedAt?: string;
}

// What the API expects in the request body when creating/updating a perfume
// (id, createdAt, updatedAt are generated by the server — not sent by the client)
export type CreatePerfumeDTO = Omit<Perfume, "id" | "createdAt" | "updatedAt">;
export type UpdatePerfumeDTO = Partial<CreatePerfumeDTO>;

export type UserRole = "admin" | "staff";

// What we store in the DB and return from the API (never includes passwordHash)
export interface User {
  id: string;
  username: string;
  role: UserRole;
  createdAt: string;
}

// Raw DB row — includes the hash (never sent to client)
export interface UserRow {
  id: string;
  username: string;
  password_hash: string;
  role: UserRole;
  created_at: string;
}

// What's encoded inside the JWT token
export interface JwtPayload {
  id: string;
  username: string;
  role: UserRole;
}

// Request bodies
export interface LoginDTO {
  username: string;
  password: string;
}

export interface CreateUserDTO {
  username: string;
  password: string;
  role: UserRole;
}

/**
 * Extends Express's Request type so req.user is available in controllers
 * after the auth middleware has verified the token.
 *
 * Without this, TypeScript would complain that req.user doesn't exist
 * on the standard Request type.
 */
declare global {
  namespace Express {
    interface Request {
      user?: JwtPayload;
    }
  }
}
